version: '3.5'

networks:
  strio-bot:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:13.8-alpine
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - strio-bot
    command: >
      postgres -c log_statement=all -c log_duration=on
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  server:
    container_name: server
    image: strio-bot-back:latest
    restart: always
    ports:
      - "3001:3000"
    working_dir: /usr/src/app
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - strio-bot


volumes:
  postgres-data:
    name: strio-bot-pg-volume
    driver: local

